version: '3.9'

services:
  service:
    build:
      dockerfile: ./Dockerfile
    container_name: service
    environment:
      - DATABASE_URI=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - HTTP_ADDRESS=${HTTP_ADDRESS}
      - GRPC_ADDRESS=${GRPC_ADDRESS}
    env_file: .env
    ports:
      - '8000:8000'
      - '9000:9000'
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      database:
        condition: service_started

  database:
    image: postgres:latest
    container_name: postgres
    restart: on-failure
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'