// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mock; is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v4 "github.com/labstack/echo/v4"
)

// MockHandlers is a mock of Handlers interface.
type MockHandlers struct {
	ctrl     *gomock.Controller
	recorder *MockHandlersMockRecorder
}

// MockHandlersMockRecorder is the mock recorder for MockHandlers.
type MockHandlersMockRecorder struct {
	mock *MockHandlers
}

// NewMockHandlers creates a new mock instance.
func NewMockHandlers(ctrl *gomock.Controller) *MockHandlers {
	mock := &MockHandlers{ctrl: ctrl}
	mock.recorder = &MockHandlersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlers) EXPECT() *MockHandlersMockRecorder {
	return m.recorder
}

// GetShortenedLink mocks base method.
func (m *MockHandlers) GetShortenedLink(c v4.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShortenedLink", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetShortenedLink indicates an expected call of GetShortenedLink.
func (mr *MockHandlersMockRecorder) GetShortenedLink(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShortenedLink", reflect.TypeOf((*MockHandlers)(nil).GetShortenedLink), c)
}

// ShortenLink mocks base method.
func (m *MockHandlers) ShortenLink(c v4.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShortenLink", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// ShortenLink indicates an expected call of ShortenLink.
func (mr *MockHandlersMockRecorder) ShortenLink(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShortenLink", reflect.TypeOf((*MockHandlers)(nil).ShortenLink), c)
}

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetShortenedLink mocks base method.
func (m *MockService) GetShortenedLink(id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShortenedLink", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShortenedLink indicates an expected call of GetShortenedLink.
func (mr *MockServiceMockRecorder) GetShortenedLink(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShortenedLink", reflect.TypeOf((*MockService)(nil).GetShortenedLink), id)
}

// ShortenLink mocks base method.
func (m *MockService) ShortenLink(link string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShortenLink", link)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShortenLink indicates an expected call of ShortenLink.
func (mr *MockServiceMockRecorder) ShortenLink(link interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShortenLink", reflect.TypeOf((*MockService)(nil).ShortenLink), link)
}

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}
